# Generated by Django 5.1.5 on 2025-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_game_seller_alter_game_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
