# Generated by Django 5.1.5 on 2025-01-18 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_game_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.AddField(
            model_name='game',
            name='add_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
