# Generated by Django 5.1.5 on 2025-01-18 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
